{% set version = "1.7-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gridsvg
  version: {{ version|replace("-", "_") }}

source:
  fn: gridSVG_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gridSVG_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gridSVG/gridSVG_{{ version }}.tar.gz
  sha256: 0f8a4ef642f4da92c908acdb98f1c4b80ea9142a66b2da776efe814a81402a0f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-xml
    - r-jsonlite
  run:
    - r-base
    - r-xml
    - r-jsonlite

test:
  commands:
    - $R -e "library('gridSVG')"           # [not win]
    - "\"%R%\" -e \"library('gridSVG')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gridSVG
  license: GPL
  summary: Functions to export graphics drawn with package grid to SVG format.  Additional functions
    provide access to SVG features that are not available in standard R graphics, such
    as hyperlinks,  animation, filters, masks, clipping paths, and gradient and pattern
    fills.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
