travis:
  secure:
    BINSTAR_TOKEN: WqvXPgn0B/KUxzWQSkigFgSOhMN4vQHiCxAso6ZDW9ed4yznWYSMaVJl87ARtd7TbzfyYUl1zJ754YiREGzppmYqylucOiXnbse12yDEMW+MWusSPF1dy+Vu+i5vZXajQKLigriM36f6TQrEIZdt4QAVowC26vhpR/YQeYLB0a6zExAvmSCZsFVfvlvknM9VgsGB16M/eIQkvdAbO2V02B5s1SzNkaxWXai9pnOgTyzpCTMbc/lElHWOeNCd428hDINiEi4gGjt9qpWBeYxrw91XGWSWzYMlqpCDZ+F3dEZSBiWqX+mvwWU3N89F9vdjLQDfTafKmS3tVyaBT94L+XGtrXNcMhbKt5pn63RmOcqbALDrS2K94Fc/CJ11FMD+aZBUMBTI6tgM1xdnuqPdJEabWCYocb+dDEtQONqZqgdXmRXlijtuyA1mrxdtmzAOud2DCwkVt2fgNQB41QTnFdpqcdrVDmPsu27dOapSEOSIq0OSNKqXgcVl0O+3D3/z1xOa0e8i4yph7UfWo9Hb5F2S89Z921hCdyJnldyreiHIh0JbxwnMVKE2yhSl93cU1qcK+vqhHzRCpg6zySkyI8KoQLT/4gEPTH/Sjss0vxG/Ui9wxYUQi7yQ1pGFFNuE3gZ44Lufv3nmHPQ3Un458y8NZZPBL5i+NiM+rrrP2eA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
