travis:
  secure:
    BINSTAR_TOKEN: VpasVKu5MttKjJ/ebwpiY81BBQQDSIO3tV5fhxB3tZSqZw6wO9KVdfFfpMWpoklf/UjPXmHVz+KhGJb4mUHBoeG3QIvxT/uPFmHCI+jWQMTRN/3KuMy/C3l1394YC7p3/QrN5lom59MbaZbD+UdLCryo+WjQtxrghUu3Fb08p6PSWCBUIsjDC+yv7vegrB01ruEj1K3Ak8QpUWX6+Q+3mqX+8cr/xUPeKSZ6ZV/3ZESZ3dvfHciIl7+8dMqpWl+mlFGzL2HM5U7lWIMprHmvlRG7qdYyMsNQCc4Fcd84JceMwb/hwgOLq38O/1c/YeorOVjw3BcyvaJryMCfz1oX/ih93rLnP9gDsYc9//ohOAlcPcRFqVOdc/4CxZjgZilcL8Q5lNqGKJWcxB6TKDT/06aKOGwer6BTvnWI6VPZzwMxk3UaKxRz+LgBFDYv5L4MghhVsQnCCOBrOKvGVRoYyVV0KqYCmxoG3GUEWat96/BjbKpkkbz6uvZou0sQxoHOVjoyKjUZ6oZvIE2Blds2hCe21E1PXihOaZ+sruZjEWPyeqX16NEwNSogQ+vS6NN0r93x+3CgOIimSY2657oON/YpFhJ/vgGQYYVo3KFnrpfpXNzOfANa3upLVhC6LPG2LvPa6q2HtPBb4mQv83NG/rfuNjT8vT3M/Xmg60ZL/mY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
