appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: sYlc5wp1CN7cKq9Nq2uTsq/sv23gsuieCxPqwfzUuHUe+HOAO0wsp4/WcmyAWBf7FWo+hYlR/rlxjXtvqr8PP7FGan48I7jcYAFdQ+snhYrtUgDBTylC3Zq+2zr8IJ/Ge3sZ3WGmE8KeXBb3wwz0k1J7MM9EXGNepDZolMyVuTyckNTuHQ1+VsrgFftJycpDwhJ0hgfYuqkH+T0WLlS2DN9//Ip6uzkwLGqtMoe4XZPA2gbByB6laVLxwbO76OwoxuIFM82KLDUeSc9dSfHZG4OjV4eX3kM57vP7QJAfUXXEQh3Bfgj/jJPpC8nTcJQ5onk6RGRclEJmgf9nQBqxsc7pPUqiLFKUnKPF9A0QZDDzL5sRau0gxeXtyL7Pd+Q3Oj3e4odRoEz09h1NWVyZhPZsdo3BZz7m3rZn+iZf/QORX7QBmb6brXdE7pR5aPopjNYlRxsR8mQ/C405sIxkfGaW3iyeH2gD52oLT31Jgq1HoKJ70Bpc/YVfFX8K+3LfbgWdOrnNtO5T6wFgeyJAqEOe2tOHbPdqQJp73MAXAl0y2yd0daTxu7iDRDqCpaGCgCEcWPAK4r47eTAXwtd0HWay+NVkt++sfTjtgbuUND9s50FCvCLhXukGer26Bo51FhgUowm64AN9GNBYC/3KpNe5vrB4nDTVQ8cYspXlqpE=}
bot:
  automerge: true
