travis:
  secure:
    BINSTAR_TOKEN: KpqeerfAZ/q8zAmrZT4XigDQJENbIRjHh6FN/sh6jzBRvdugjXMCoMOaUJt5xbeA3zvrdJgEPERNTexdaxXa7dMK6cKfBsJIbMxI+kerJ+ozUNALdnMRgEeCm0ZZqaxEY4yLhwy7BX7jdnmHdgVeDefmxEC+n7SehMX4JiPvF+9p0X2oghzxR519tbIbR/7xeV2VsB0mg9ZUi8CCkJEYCwTuDM5PmpIbDp75nkqd8QmgHyVLZ1hsghB9qgLqg1ftipEkWmw6SJw0Z8NreH9l0YtxIOZgDyMLiVpyjHZXK8hJwxnkznqdKqHcnacBAvif5icdCg+zeQriYRhmJCV0DxRo10lG4g8XCHv3pcmuclNIinlYdmNhbT/W66hi4BqhHs3Cfe5UUVAfTbv0FzSemSwDU7oKvVpE679nc6dRQaDgBgb6RtSalfg+z4fUYQFY4ZINoPyczMx8u6IbhfTYgaFuRlxCp2ybygncJhjbH7/7GpkDT2f2SrPQl+5lWPy9uuHU9j+O+YKl4hX0DlSHPIRWGB5In0lJ1R4fJGDfcFEYGEzJ7XZddMsZq2Zg8qlbj/4k3RYv5jCoSapwgOXKYaLyiJfXmVs79yPesyTcZ6thGVaiLmhPRHt+MpimVAtV2XzWHA581cJ329WDUDYGthudzV2goICk27lvTQDtIWM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
